# Converting dat files into csv

In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

In [44]:
file = open('zipcombo.dat', 'r')         #open the zipcombo.dat file

data = np.array([])

row = 0
for line in file.readlines():            #each line corresponds to one sample
    elements = line.split(" ")           #feature are seperated by blanks
    elements = elements[:-1]             #remove the \n at the end
    elements = np.array(elements, dtype=float)
    data = np.append(data, elements)
    row += 1
file.close()                             #close the file

col = len(elements)
data = data.reshape(row, col)            #reshape the dataset
df = pd.DataFrame(data=data)             #store the data in a dataframe
df = df.rename(columns={0: 'label'})
df.to_csv('zipcombo.csv', index=False)   #save the dataframe as a csv file

In [4]:
file = open('dtrain13_50.dat', 'r') 

data = np.array([])

row = 0
for line in file.readlines():
    elements = line.split("\t")
    elements[-1] = elements[-1][:-1]
    if elements[0] == '3':
        elements[0] = '-1'
    elements = np.array(elements, dtype=float)
    data = np.append(data, elements)
    row += 1
file.close()

col = len(elements)
data = data.reshape(row, col)
df = pd.DataFrame(data=data)             #store the data in a dataframe
df = df.rename(columns={0: 'label'})
df.to_csv('dtrain13_50.csv', index=False)  
df.head()

,label,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,256
0,1.0,-0.999991,-0.999341,-0.987314,-0.908872,-0.673858,-0.297294,-0.007564,0.028120,0.143432,...,-0.029774,0.182808,0.288497,0.303225,0.296620,0.215770,-0.085411,-0.520507,-0.863179,-0.983402
1,1.0,-1.000000,-1.000000,-0.999925,-0.994087,-0.901781,-0.532422,0.030343,0.218092,-0.284764,...,0.480413,0.503431,0.372348,0.039117,-0.396256,-0.760836,-0.949353,-0.996077,-0.999891,-0.999999
2,1.0,-0.999968,-0.998899,-0.979645,-0.808860,-0.300545,0.253946,0.426475,0.221106,-0.109287,...,0.219153,0.439904,0.413636,0.143188,-0.236744,-0.645292,-0.902481,-0.986311,-0.999285,-0.999990
3,1.0,-1.000000,-0.999997,-0.999734,-0.992537,-0.918866,-0.642963,-0.178492,0.070579,-0.301935,...,0.424630,0.460490,0.247884,-0.104805,-0.498261,-0.835439,-0.975208,-0.998513,-0.999955,-0.999999
4,1.0,-1.000000,-1.000000,-0.999989,-0.999212,-0.982739,-0.848530,-0.417635,0.094446,0.130927,...,0.065153,0.184270,0.421109,0.427925,0.158026,-0.165007,-0.519464,-0.825121,-0.966519,-0.997219

In [6]:
file = open('dtrain13_100.dat', 'r') 

data = np.array([])

row = 0
for line in file.readlines():
    elements = line.split("\t")
    elements[-1] = elements[-1][:-1]
    if elements[0] == '3':
        elements[0] = '-1'
    elements = np.array(elements, dtype=float)
    data = np.append(data, elements)
    row += 1
file.close()

col = len(elements)
data = data.reshape(row, col)
df = pd.DataFrame(data=data)             #store the data in a dataframe
df = df.rename(columns={0: 'label'})
df.to_csv('dtrain13_100.csv', index=False)  
df.head()

,label,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,256
0,1.0,-1.000000,-1.000000,-0.999970,-0.998548,-0.968473,-0.709550,-0.072981,0.263648,-0.086948,...,0.176490,0.421207,0.416646,0.184395,-0.014236,-0.291833,-0.572951,-0.858159,-0.979850,-0.998268
1,1.0,-0.999985,-0.999178,-0.985787,-0.910990,-0.704129,-0.363842,0.042870,0.405129,0.522815,...,-0.111306,0.293946,0.481073,0.432018,0.096583,-0.405313,-0.800046,-0.965297,-0.997787,-0.999954
2,1.0,-1.000000,-0.999998,-0.999904,-0.996492,-0.954201,-0.819162,-0.679237,-0.673463,-0.800922,...,-0.742627,-0.689040,-0.714932,-0.796509,-0.906126,-0.966978,-0.986447,-0.995587,-0.999266,-0.999946
3,1.0,-1.000000,-1.000000,-0.999961,-0.996425,-0.929633,-0.537787,0.182302,0.355600,-0.056980,...,-0.033016,0.340419,0.456195,0.301825,-0.076203,-0.550731,-0.883261,-0.987393,-0.999417,-0.999989
4,1.0,-1.000000,-0.999982,-0.998283,-0.962328,-0.705499,-0.137200,0.176236,0.069655,-0.256916,...,0.378137,0.506226,0.480764,0.228400,-0.317374,-0.781385,-0.964692,-0.997792,-0.999953,-1.000000

In [8]:
file = open('dtrain13_200.dat', 'r') 

data = np.array([])

row = 0
for line in file.readlines():
    elements = line.split("\t")
    elements[-1] = elements[-1][:-1]
    if elements[0] == '3':
        elements[0] = '-1'
    elements = np.array(elements, dtype=float)
    data = np.append(data, elements)
    row += 1
file.close()

col = len(elements)
data = data.reshape(row, col)
df = pd.DataFrame(data=data)             #store the data in a dataframe
df = df.rename(columns={0: 'label'})
df.to_csv('dtrain13_200.csv', index=False)  
df.head()

,label,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,256
0,1.0,-0.999907,-0.996364,-0.951282,-0.772158,-0.411941,0.057381,0.320406,0.206868,0.020278,...,0.523823,0.446470,0.241600,0.067170,-0.205598,-0.530276,-0.771355,-0.921468,-0.985030,-0.998721
1,1.0,-0.999997,-0.999836,-0.996528,-0.966639,-0.849667,-0.624200,-0.387293,-0.184032,-0.014601,...,-0.284576,0.091032,0.372790,0.462428,0.360255,0.049194,-0.450620,-0.826805,-0.971184,-0.998192
2,1.0,-1.000000,-0.999998,-0.999858,-0.996755,-0.970201,-0.866432,-0.654058,-0.284348,0.148610,...,0.431632,0.507654,0.485989,0.349383,0.012679,-0.430345,-0.797961,-0.964444,-0.998024,-0.999978
3,1.0,-0.999999,-0.999858,-0.992576,-0.887693,-0.464161,0.146866,0.336521,0.072316,-0.344309,...,0.309854,0.436969,0.347829,-0.064176,-0.459943,-0.744826,-0.929899,-0.991755,-0.999557,-0.999990
4,1.0,-1.000000,-1.000000,-0.999997,-0.999765,-0.995366,-0.966341,-0.856580,-0.549132,-0.020835,...,-0.064041,0.349407,0.488400,0.415299,0.178058,-0.167650,-0.636970,-0.927567,-0.995794,-0.999952

In [7]:
file = open('dtrain13_400.dat', 'r') 

data = np.array([])

row = 0
for line in file.readlines():
    elements = line.split("\t")
    elements[-1] = elements[-1][:-1]
    if elements[0] == '3':
        elements[0] = '-1'
    elements = np.array(elements, dtype=float)
    data = np.append(data, elements)
    row += 1
file.close()

col = len(elements)
data = data.reshape(row, col)
df = pd.DataFrame(data=data)             #store the data in a dataframe
df = df.rename(columns={0: 'label'})
df.to_csv('dtrain13_400.csv', index=False)  
df.head()

,label,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,256
0,1.0,-1.0,-0.999996,-0.999596,-0.987691,-0.861417,-0.442911,0.072731,0.218784,-0.101458,...,-0.019881,0.061762,-0.156459,-0.606277,-0.913287,-0.993369,-0.999822,-0.999998,-1.000000,-1.000000
1,1.0,-1.0,-1.000000,-0.999998,-0.999716,-0.985265,-0.792226,-0.213673,0.202345,-0.097867,...,0.061457,0.362927,0.379315,0.048284,-0.453635,-0.840385,-0.978567,-0.998810,-0.999976,-1.000000
2,1.0,-1.0,-1.000000,-1.000000,-0.999994,-0.999512,-0.980430,-0.748862,-0.150863,0.094464,...,0.195667,0.439291,0.499530,0.497185,0.319665,-0.248137,-0.791492,-0.977688,-0.999054,-0.999987
3,1.0,-1.0,-0.999998,-0.999865,-0.997155,-0.970899,-0.784816,-0.246663,0.321898,0.373867,...,0.103308,0.419997,0.514265,0.420840,0.094522,-0.337477,-0.691415,-0.916340,-0.990547,-0.999598
4,1.0,-1.0,-0.999999,-0.999956,-0.998749,-0.971801,-0.680891,-0.076295,-0.117938,-0.569606,...,0.374241,0.200382,-0.056465,-0.251138,-0.447943,-0.802686,-0.972829,-0.997832,-0.999912,-0.999999